---
name: FHEM
version: dev
slug: fhem
description: FHEM add-on by Community Home Assistant Add-ons
url: https://github.com/mipxx/addon-fhem
init: false
ingress: false
ingress_port: 0
ingress_stream: false
host_network: true
ports:
  8083/tcp: 8083
ports_description:
  8083/tcp: 8083
uart: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386